### ISSUE TITLE
organization 作成時のエラー

### ISSUE THREAD

**Issue by TabeteSuguneru** [mtmtkj/okr_laravel#53]
organizationを作成しようとすると以下のエラーがでる。
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'q' in 'field list' (SQL: insert into `organizations` (`name`, `q`, `updated_at`, `created_at`) values (stal, /organization, 2017-12-18 22:42:48, 2017-12-18 22:42:48))
```
どうやら
https://github.com/mtmtkj/okr_laravel/blob/8a1fc0d70a2fcdb969a5b90f506e4b736525dd36/app/Http/Controllers/OrganizationController.php#L17
>$request->data();

がいけないらしい。

**Comment by TabeteSuguneru** [comment]
@mtmtkj @TsukasaGR 

1.修正方針
data()だとquery？まで入っていて、登録でエラーになっているので
>$organization = Organization::create(['name'=>$request->name]);

に修正しちゃって大丈夫ですかね？

2.data()の使い所
察するにdata()はrequestの中から`_token`とか除いた登録対象のデータだけ取り出すものかと思ったのですが、違うんでしょうか？

**Comment by mtmtkj** [comment]
@YumaKimura 上記1、OKです。2 YES! です

**Comment by TabeteSuguneru** [comment]
@mtmtkj 
>2 YES! です

だとすると、
> $request->data()

の返り値に`request->query->all()`の返り値も含まれているのはなぜでしょうか？？？
今回のように登録する時に、data()使えないですよね？？

**Comment by mtmtkj** [comment]
@YumaKimura 

> 返り値にrequest->query->all()の返り値も含まれているのはなぜでしょうか？？？
> 今回のように登録する時に、data()使えないですよね？？

request->except() が query の値も入れちゃってるからですね、おそらく、request->input()->except() で採る必要あるかな、と推測してます
